apiVersion: v1
kind: Namespace
metadata:
  name: evertwine
  labels:
    name: evertwine
    environment: production
    app: evertwine
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: evertwine-quota
  namespace: evertwine
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: evertwine-limits
  namespace: evertwine
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      type: Container
