global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Backend API
  - job_name: "backend"
    static_configs:
      - targets: ["backend:3001"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  # Frontend (if exposing metrics)
  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:3000"]
    metrics_path: "/metrics"
    scrape_interval: 15s

  # PostgreSQL (using postgres_exporter)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s

  # Redis (using redis_exporter)
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 30s

  # Node.js application metrics
  - job_name: "nodejs"
    static_configs:
      - targets: ["backend:3001"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  # Docker containers
  - job_name: "docker"
    static_configs:
      - targets: ["docker-exporter:9323"]
    scrape_interval: 30s

  # Nginx metrics
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
    scrape_interval: 30s

  # System metrics (if using node_exporter)
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
