name: CI

on:
  push:
    branches: [main, develop, devops-practice-environment]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      # Frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Lint frontend
        working-directory: ./frontend
        run: npm run lint

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Backend
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Lint backend
        working-directory: ./backend
        run: npm run lint --if-present || echo "No backend linting configured"

      # Test Docker builds
      - name: Test Docker builds
        run: |
          docker build -t evertwine-frontend:test ./frontend
          docker build -t evertwine-backend:test ./backend
          echo "✅ Docker builds successful"
