name: Security Scan

on:
  push:
    branches: [main, develop, devops-practice-environment]
  pull_request:
    branches: [main]
  schedule:
    # Run security scans weekly
    - cron: "0 2 * * 1"

# Minimal permissions for this workflow
permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        # Upload only when we have a token with security-events: write (e.g., push/schedule).
        if: ${{ always() && github.event_name != 'pull_request' }}
        with:
          sarif_file: "trivy-results.sarif"
          wait-for-processing: true

      - name: Upload SARIF as artifact (PRs)
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results.sarif
          path: trivy-results.sarif
          if-no-files-found: ignore
          retention-days: 7

      - name: Run npm audit for frontend
        working-directory: ./frontend
        run: npm audit --audit-level=moderate

      - name: Run npm audit for backend
        working-directory: ./backend
        run: npm audit --audit-level=moderate

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
        continue-on-error: true

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate
